---
- name: setup a hpc cluster in openstack
  hosts: os_ctrl
  tags: provision
  roles: 
    - provision

- name: configure the new virtual machines
  hosts: cluster
  tags: configure
  roles: 
    - configure_hpc

